!!python/object:__main__.Args
alpha: 0.5
aug_ratio: 16
batch_size: 512
buffer_size: 2000000
capture_video: false
cuda: true
daf: RelabelGoal
env_id: PandaSlide-v3
env_kwargs: {}
eval_freq: 10000
exp_name: ddpg
exploration_noise: 0.2
gamma: 0.95
learning_rate: 0.001
learning_starts: 1000.0
n_eval_episodes: 80
net_arch: !!python/tuple
- 256
- 256
- 256
noise_clip: 0.5
random_action_prob: 0.3
run_id: 41
save_dir: results/PandaSlide-v3/ddpg/2xViaTranslateGoal/run_41
save_model: false
save_rootdir: results
save_subdir: 2xViaTranslateGoal
seed: 3736644555
tau: 0.05
torch_deterministic: true
total_timesteps: 1000000
track: false
train_freq: 2
wandb_entity: null
wandb_project_name: cleanRL
